### ISSUE TITLE
Error executing process > 'put_rnaseq_into_ribo'

### ISSUE THREAD

**Issue by imilenkovic** [ribosomeprofiling/riboflow#18]
Hello,

I tried running the pipeline on RiboSeq+RNAseq data, and it ran until almost the end when it failed:

```
Error executing process > 'put_rnaseq_into_ribo (1)'

Caused by:
  Process `put_rnaseq_into_ribo (1)` terminated with an error exit status (1)

Command executed:

  ribopy rnaseq set -n KO -a KO.merged.pre_dedup.bed -f bed --force KO.ribo

Command exit status:
  1

Command output:
  (empty)

Command error:
  + ribopy rnaseq set -n KO -a KO.merged.pre_dedup.bed -f bed --force KO.ribo
  Traceback (most recent call last):
    File "/miniconda3/bin/ribopy", line 10, in <module>
      sys.exit(cli())
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
      return self.main(*args, **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
      rv = self.invoke(ctx)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
      return _process_result(sub_ctx.command.invoke(su[9d/b03848] Submitted process > put_rnaseq_into_ribo (2)
/click/core.py", line 1137, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/miniconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
      return callback(*args, **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/ribopy/cli/rnaseq.py", line 54, in set
      force         = force)
    File "/miniconda3/lib/python3.6/site-packages/ribopy/core/verify.py", line 104, in cli_func_wrapper
      return func(*args, **kwargs)
    File "/miniconda3/lib/python3.6/site-packages/ribopy/rnaseq.py", line 229, in set_rnaseq_wrapper
      with h5py.File(ribo_file, "r+") as ribo_handle:
    File "/miniconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
      swmr=swmr)
    File "/miniconda3/lib/python3.6/site-packages/h5py/_hl/files.py", line 172, in make_fid
      fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
    File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    File "h5py/h5f.pyx", line 85, in h5py.h5f.open
  OSError: Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')

Work dir:
  /nfs/users2/enovoa/imilenkovic/software/riboflow/riboflow/work/45/f654e3edc0b937986d14d450917fcf

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

Pipeline RiboFlow completed!
Started at  2021-03-24T00:07:38.048+01:00
Finished at 2021-03-24T01:25:25.332+01:00
Time elapsed: 1h 17m 47s
Execution status: failed
WARN: Killing pending tasks (1)

```

Do you maybe have an idea what went wrong? Thank you!

**Comment by imilenkovic** [comment]
I relized I accidently ran the pipeline while it was already running, so the files were already there and it caused h5py to complain.
