### ISSUE TITLE
Errors running example data on umi_devel branch

### ISSUE THREAD

**Issue by ijhoskins** [ribosomeprofiling/riboflow#24]
Hi @hakanozadam ,

I tried doing a fresh install of Riboflow umi_devel on Mozart but ran into errors running the example data. I am running via conda.

Looks like one issue is FASTQC files are not found for the process transcriptome_aligned_individual_fastqc:

```
nextflow RiboFlow.groovy -params-file project.yaml
N E X T F L O W  ~  version 19.04.1
Launching `RiboFlow.groovy` [marvelous_easley] - revision: 1eb5b20f2c
[warm up] executor > local
[skipping] Stored process > clip (4)
[skipping] Stored process > clip (3)
[skipping] Stored process > clip (2)
[skipping] Stored process > clip (1)
[skipping] Stored process > extract_umi_via_umi_tools (1)
[skipping] Stored process > extract_umi_via_umi_tools (3)
[skipping] Stored process > extract_umi_via_umi_tools (2)
[skipping] Stored process > extract_umi_via_umi_tools (4)
[skipping] Stored process > filter (1)
[skipping] Stored process > filter (2)
[skipping] Stored process > filter (3)
[skipping] Stored process > filter (4)
[skipping] Stored process > transcriptome_alignment (2)
[skipping] Stored process > transcriptome_alignment (1)
[skipping] Stored process > transcriptome_alignment (3)
[skipping] Stored process > transcriptome_alignment (4)
[skipping] Stored process > merge_transcriptome_alignment (1)
[skipping] Stored process > merge_transcriptome_alignment (2)
executor >  local (14)
executor >  local (15)
[47/2cad5f] process > clipped_fastqc                            [100%] 4 of 4 ✔
executor >  local (17)
[47/2cad5f] process > clipped_fastqc                            [100%] 4 of 4 ✔
[c5/fbec5c] process > raw_fastqc                                [100%] 4 of 4 ✔
executor >  local (18)
[47/2cad5f] process > clipped_fastqc                            [100%] 4 of 4 ✔
[c5/fbec5c] process > raw_fastqc                                [100%] 4 of 4 ✔
executor >  local (19)
[47/2cad5f] process > clipped_fastqc                            [100%] 4 of 4 ✔
[c5/fbec5c] process > raw_fastqc                                [100%] 4 of 4 ✔
[2f/590158] process > transcriptome_unaligned_individual_fastqc [ 50%] 2 of 4
executor >  local (21)
[47/2cad5f] process > clipped_fastqc                            [100%] 4 of 4 ✔
[c5/fbec5c] process > raw_fastqc                                [100%] 4 of 4 ✔
[53/15cc5f] process > transcriptome_unaligned_individual_fastqc [ 75%] 3 of 4
[47/c9d300] process > write_fastq_correspondence                [100%] 1 of 1 ✔
[7b/40c88b] process > transcriptome_aligned_individual_fastqc   [ 50%] 4 of 8, failed: 4
[92/0631c4] NOTE: Missing output file(s) `GSM1606108.1.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (1)` -- Execution is retried (1)
[a4/308e18] NOTE: Missing output file(s) `GSM1606107.1.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (2)` -- Execution is retried (1)
executor >  local (21)
[47/2cad5f] process > clipped_fastqc                            [100%] 4 of 4 ✔
[c5/fbec5c] process > raw_fastqc                                [100%] 4 of 4 ✔
[cd/3bddd9] process > transcriptome_unaligned_individual_fastqc [100%] 4 of 4, failed: 1
[47/c9d300] process > write_fastq_correspondence                [100%] 1 of 1 ✔
[7b/40c88b] process > transcriptome_aligned_individual_fastqc   [100%] 8 of 8, failed: 8
[92/0631c4] NOTE: Missing output file(s) `GSM1606108.1.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (1)` -- Execution is retried (1)
[a4/308e18] NOTE: Missing output file(s) `GSM1606107.1.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (2)` -- Execution is retried (1)
[78/401fec] NOTE: Missing output file(s) `GSM1606108.2.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (3)` -- Execution executor >  local (21)
[47/2cad5f] process > clipped_fastqc                            [100%] 4 of 4 ✔
[c5/fbec5c] process > raw_fastqc                                [100%] 4 of 4 ✔
[cd/3bddd9] process > transcriptome_unaligned_individual_fastqc [100%] 4 of 4, failed: 1
[47/c9d300] process > write_fastq_correspondence                [100%] 1 of 1 ✔
[7b/40c88b] process > transcriptome_aligned_individual_fastqc   [100%] 8 of 8, failed: 8
[92/0631c4] NOTE: Missing output file(s) `GSM1606108.1.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (1)` -- Execution is retried (1)
[a4/308e18] NOTE: Missing output file(s) `GSM1606107.1.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (2)` -- Execution is retried (1)
[78/401fec] NOTE: Missing output file(s) `GSM1606108.2.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (3)` -- Execution is retried (1)
[e5/a6ed71] NOTE: Missing output file(s) `GSM1606107.2.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (4)` -- Execution is retried (1)
WARN: Killing pending tasks (4)
ERROR ~ Error executing process > 'transcriptome_aligned_individual_fastqc (1)'

Caused by:
  Missing output file(s) `GSM1606108.1.transcriptome.aligned_fastqc.html` expected by process `transcriptome_aligned_individual_fastqc (1)`

Command executed:

  if [ ! -f GSM1606108.1.transcriptome.aligned.fastq.gz ]; then
     ln -s GSM1606108.1.aligned.transcriptome_alignment.fastq.gz GSM1606108.1.transcriptome.aligned.fastq.gz
  fi
  fastqc GSM1606108.1.transcriptome.aligned.fastq.gz --outdir=$PWD -t 1

Command exit status:
  0

Command output:
  Analysis complete for GSM1606108.1.transcriptome.aligned.fastq.gz

Command error:
  + '[' '!' -f GSM1606108.1.transcriptome.aligned.fastq.gz ']'
  + ln -s GSM1606108.1.aligned.transcriptome_alignment.fastq.gz GSM1606108.1.transcriptome.aligned.fastq.gz
  + fastqc GSM1606108.1.transcriptome.aligned.fastq.gz --outdir=/home/ihoskins/riboflow_umi/riboflow/work/29/b062e85fb941e26442063b70a3d1b8 -t 1
  Started analysis of GSM1606108.1.transcriptome.aligned.fastq.gz
  Failed to process file GSM1606108.1.transcriptome.aligned.fastq.gz
  java.lang.ArrayIndexOutOfBoundsException: -1
  p: wheat uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.calculateDistribution(SequenceLengthDistribution.java:101)
  	at uk.ac.babraham.FastQC.Modules.SequenceLengthDistribution.raisesError(SequenceLengthDistribution.java:190)
  - Checat uk.ac.babraham.FastQC.Report.HTMLReportArchive.startDocument(HTMLReportArchive.java:336)
  	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:84)
  	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
  	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
  	at java.lang.Thread.run(Thread.java:750)

Work dir:
  /home/ihoskins/riboflow_umi/riboflow/work/29/b062e85fb941e26442063b70a3d1b8

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details
```

Then, if I set do_fastqc = False, I run into an error during deduplication:

```
nextflow RiboFlow.groovy -params-file project.yaml
N E X T F L O W  ~  version 19.04.1
Launching `RiboFlow.groovy` [insane_watson] - revision: 1eb5b20f2c
[warm up] executor > local
[skipping] Stored process > clip (4)
[skipping] Stored process > clip (3)
[skipping] Stored process > clip (1)
[skipping] Stored process > clip (2)
[skipping] Stored process > extract_umi_via_umi_tools (1)
[skipping] Stored process > extract_umi_via_umi_tools (2)
[skipping] Stored process > extract_umi_via_umi_tools (3)
[skipping] Stored process > extract_umi_via_umi_tools (4)
[skipping] Stored process > filter (2)
[skipping] Stored process > filter (1)
[skipping] Stored process > filter (3)
[skipping] Stored process > filter (4)
[skipping] Stored process > transcriptome_alignment (2)
[skipping] Stored process > transcriptome_alignment (1)
[skipping] Stored process > transcriptome_alignment (3)
[skipping] Stored process > transcriptome_alignment (4)
[skipping] Stored process > merge_transcriptome_alignment (1)
[skipping] Stored process > merge_transcriptome_alignment (2)
executor >  local (19)
[01/51ddee] process > write_fastq_correspondence  [100%] 1 of 1 ✔
[f8/7325fa] process > quality_filter              [100%] 4 of 4 ✔
[b1/af98e0] process > bam_to_bed                  [100%] 4 of 4 ✔
[8d/2ca045] process > merge_bam_post_qpass        [100%] 2 of 2 ✔
[9a/070bfd] process > add_sample_index_col_to_bed [100%] 4 of 4 ✔
[46/1950df] process > deduplicate_umi_tools       [ 50%] 2 of 4, failed: 2
executor >  local (19)
[01/51ddee] process > write_fastq_correspondence  [100%] 1 of 1 ✔
[f8/7325fa] process > quality_filter              [100%] 4 of 4 ✔
[b1/af98e0] process > bam_to_bed                  [100%] 4 of 4 ✔
[8d/2ca045] process > merge_bam_post_qpass        [100%] 2 of 2 ✔
[9a/070bfd] process > add_sample_index_col_to_bed [100%] 4 of 4 ✔
[44/491ce9] process > deduplicate_umi_tools       [100%] 4 of 4, failed: 4
[da/f6a586] NOTE: Process `deduplicate_umi_tools (2)` terminated with an error exit status (1) -- Execution is retried (1)
executor >  local (19)
[01/51ddee] process > write_fastq_correspondence  [100%] 1 of 1 ✔
[f8/7325fa] process > quality_filter              [100%] 4 of 4 ✔
[b1/af98e0] process > bam_to_bed                  [100%] 4 of 4 ✔
[8d/2ca045] process > merge_bam_post_qpass        [100%] 2 of 2 ✔
[9a/070bfd] process > add_sample_index_col_to_bed [100%] 4 of 4 ✔
[44/491ce9] process > deduplicate_umi_tools       [100%] 4 of 4, failed: 4
[da/f6a586] NOTE: Process `deduplicate_umi_tools (2)` terminated with an error exit status (1) -- Execution is retried (1)
[57/252c60] NOTE: Process `deduplicate_umi_tools (1)` terminated with an error exit status (1) -- Execution is retried (1)
WARN: Killing pending tasks (1)
ERROR ~ Error executing process > 'deduplicate_umi_tools (1)'

Caused by:
  Process `deduplicate_umi_tools (1)` terminated with an error exit status (1)

Command executed:

  umi_tools dedup --read-length               -I GSM1606107.merged.pre_dedup.bam --output-stats=GSM1606107.dedup.stats -S GSM1606107.dedup.bam -L GSM1606107.dedup.log
  
  bamToBed -i GSM1606107.dedup.bam > GSM1606107.dedup.bed

Command exit status:
  1

Command output:
  (empty)

Command error:
  + umi_tools dedup --read-length -I GSM1606107.merged.pre_dedup.bam --output-stats=GSM1606107.dedup.stats -S GSM1606107.dedup.bam -L GSM1606107.dedup.log
  Traceback (most recent call last):
    File "/home/ihoskins/miniconda3/envs/ribo_umi/bin/umi_tools", line 11, in <module>
      sys.exit(main())
    File "/home/ihoskins/miniconda3/envs/ribo_umi/lib/python3.6/site-packages/umi_tools/umi_tools.py", line 66, in main
      module.main(sys.argv)
    File "/home/ihoskins/miniconda3/envs/ribo_umi/lib/python3.6/site-packages/umi_tools/dedup.py", line 312, in main
      barcode_getter=bundle_iterator.barcode_getter)
    File "/home/ihoskins/miniconda3/envs/ribo_umi/lib/python3.6/site-packages/umi_tools/umi_methods.py", line 187, in __init__
      self.fill()
    File "/home/ihoskins/miniconda3/envs/ribo_umi/lib/python3.6/site-packages/umi_tools/umi_methods.py", line 220, in fill
      self.refill_random()
    File "/home/ihoskins/miniconda3/envs/ribo_umi/lib/python3.6/site-packages/umi_tools/umi_methods.py", line 192, in refill_random
      list(self.umis.keys()), self.random_fill_size, p=self.prob)
    File "mtrand.pyx", line 908, in numpy.random.mtrand.RandomState.choice
  ValueError: 'a' cannot be empty unless no samples are taken

Work dir:
  /home/ihoskins/riboflow_umi/riboflow/work/46/1950dfa4a153305c3aca44b9d5a765

Tip: when you have fixed the problem you can continue the execution appending to the nextflow command line the option `-resume`

 -- Check '.nextflow.log' file for details
```

**Comment by hakanozadam** [comment]
The problem above was caused by runnig Riboflow on data without having the 3' adapters specified in the project file "AAAAAAAAAACAAAAAAAAAA". So, the output of the trim process was empty and this caused Fastqc part to throw an error.

I have updated Riboflow to fix the problem. 
In this new version,m we incorporate UMIs.
Now, all changes are in the main branch.
There are two separate project files for two datasets
the first is the old dataset without UMIs and the new dataset contains UMIs.
I provide documentation in README.md also.
